language: java

matrix:
  include:
    # License, formatter, and FindBugs check
    - env: NAME="License, formatter, and FindBugs check"
      os: linux
      sudo: false
      jdk: openjdk11
      script:
        - mvn license:check
        - mvn formatter:validate
        - mvn spotbugs:check

    # Linux tests
    - env: NAME="Linux tests"
      os: linux
      sudo: false
      jdk: openjdk11
      services:
        - xvfb
      script:
        - mvn test

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew

before_install:
  - rm ~/.m2/settings.xml || true # remove the default settings.xml in order to use custom repos
